name: Mainnet Deploy

on:
  push:
    branches:
      - mainnet

jobs:
  eks-helm-deploy:
    runs-on: ubuntu-latest
    environment:
      name: mainnet
    env:
      ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: ${{ secrets.CONTEXT }}

      - name: Decrypt gpg secret
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSPHRASE" --output helm/charts/besu-genesis/genesis.json
        env:
          GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}

      - name: Deploy Genesis
        run: |
          helm upgrade -i genesis-mainnet ./helm/charts/besu-genesis -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/genesis-besu.yml

      - name: Deploy Boot nodes
        run: |
          helm upgrade -i bootnode-mainnet-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/bootnode.yml
          helm upgrade -i bootnode-mainnet-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/bootnode.yml

      - name: Deploy Validators
        run: |
          helm upgrade -i validator-mainnet-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml
          helm upgrade -i validator-mainnet-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml
          helm upgrade -i validator-mainnet-3 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml
          helm upgrade -i validator-mainnet-4 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml
          helm upgrade -i validator-mainnet-5 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml
          helm upgrade -i validator-mainnet-6 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/validator.yml

      - name: Deploy Members
        run: |
          helm upgrade -i member-mainnet-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/txnode.yml
          helm upgrade -i member-mainnet-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/txnode.yml
          helm upgrade -i member-mainnet-3 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/txnode.yml

      - name: Deploy RPC
        run: |
          helm upgrade -i rpc-mainnet-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/reader.yml
          helm upgrade -i rpc-mainnet-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace --set node.besu.account.password=$ACCOUN
T_PASSWORD --set rawGenesisConfig.blockchain.accountPassword=$ACCOUNT_PASSWORD -f ./helm/mainnet-values/reader.yml

      - name: Deploy Ingress
        run: |
          kubectl apply -f ./ingress/ingress-rules-besu.yml -n ${{ vars.NAMESPACE }}