name: Testnet Deploy

on:
  push:
    branches:
      - testnet

jobs:
  eks-helm-deploy:
    runs-on: ubuntu-latest
    environment:
      name: testnet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.K8S_VERSION }}

      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.EKS_ENDPOINT }}
          k8s-secret: ${{ secrets.EKS_SA_SECRET }}

      - name: Deploy Genesis
        run: |
          helm upgrade -i genesis ./helm/charts/besu-genesis -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/genesis-besu.yml

      - name: Deploy Boot nodes
        run: |
          helm upgrade -i bootnode-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/bootnode.yml
          helm upgrade -i bootnode-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/bootnode.yml

      - name: Deploy Validators
        run: |
          helm upgrade -i validator-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/validator.yml
          helm upgrade -i validator-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/validator.yml
          helm upgrade -i validator-3 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/validator.yml
          helm upgrade -i validator-4 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/validator.yml

      - name: Deploy Members
        run: |
          helm upgrade -i member-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/txnode.yml
          helm upgrade -i member-2 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/txnode.yml
          helm upgrade -i member-3 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/txnode.yml

      - name: Deploy RPC
        run: |
          helm upgrade -i rpc-1 ./helm/charts/besu-node -n ${{ vars.NAMESPACE }} --create-namespace -f ./helm/values/reader.yml